export const fetchSongs = {
  REQUEST_CREATE_SONG: 'fetchSongs.REQUEST_CREATE_SONG',
  RECEIVE_CREATE_SONG_ERROR: 'fetchSongs.RECEIVE_CREATE_SONG_ERROR',
  REQUEST_FETCH_SONGS: 'fetchSongs.REQUEST_FETCH_SONGS',
  RECEIVE_FETCH_SONGS_ERROR: 'fetchSongs.RECEIVE_FETCH_SONGS_ERROR'
}

export const fetchSong = {
  REQUEST_FETCH_SONG: 'fetchSong.REQUEST_FETCH_SONG',
  RECEIVE_FETCH_SONG_ERROR: 'fetchSong.RECEIVE_FETCH_SONG_ERROR'
}

export const songTypes = {
  RECEIVE_CREATE_SONG: 'song.RECEIVE_CREATE_SONG',
  RECEIVE_FETCH_SONG: 'song.RECEIVE_FETCH_SONG',
  RECEIVE_FETCH_SONGS: 'song.RECEIVE_FETCH_SONGS'
}

export const tracks = {
  SET_TRACK: 'tracks.SET_TRACK'
}

export const tone = {
  LOADING: 'tone.LOADING',
  FINISHED_LOADING: 'tone.FINISHED_LOADING'
}

export const time = {
  PASS_TIME: 'time.PASS_TIME',
  TOGGLE_BOOLEAN: 'time.TOGGLE_BOOLEAN',
  START_TIME: 'time.START_TIME',
  STOP_TIME: 'time.STOP_TIME'
}
